# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ind_to_coord <- function(index, grid_nrow) {
    .Call(`_sousmarin_ind_to_coord`, index, grid_nrow)
}

coord_to_dist <- function(p1, p2) {
    .Call(`_sousmarin_coord_to_dist`, p1, p2)
}

cov_model_exp_cpp <- function(d, a = 2) {
    .Call(`_sousmarin_cov_model_exp_cpp`, d, a)
}

#' @export
cov_model_gauss <- function(d, a, m) {
    .Call(`_sousmarin_cov_model_gauss`, d, a, m)
}

#' @export
cov_model_sphere <- function(d, a, m) {
    .Call(`_sousmarin_cov_model_sphere`, d, a, m)
}

#' @export
cov_model_tent <- function(d, a, sigma) {
    .Call(`_sousmarin_cov_model_tent`, d, a, sigma)
}

#' @export
get_cov_row_exp <- function(i, grid_nrow, a = 2) {
    .Call(`_sousmarin_get_cov_row_exp`, i, grid_nrow, a)
}

#' @export
get_cov_row_gauss <- function(i, grid_nrow, a = 2, m = 1) {
    .Call(`_sousmarin_get_cov_row_gauss`, i, grid_nrow, a, m)
}

#' @export
get_cov_row_tent <- function(i, grid_nrow, a = 2, sigma = 1) {
    .Call(`_sousmarin_get_cov_row_tent`, i, grid_nrow, a, sigma)
}

#' @export
get_cov_row_sphere <- function(i, grid_nrow, a = 2, m = 1) {
    .Call(`_sousmarin_get_cov_row_sphere`, i, grid_nrow, a, m)
}

#' @export
get_cov_matrix_exp <- function(grid_nrow, a = 2) {
    .Call(`_sousmarin_get_cov_matrix_exp`, grid_nrow, a)
}

#' @export
get_cov_matrix_gauss <- function(grid_nrow, a = 2, m = 1) {
    .Call(`_sousmarin_get_cov_matrix_gauss`, grid_nrow, a, m)
}

#' @export
get_cov_matrix_sphere <- function(grid_nrow, a = 2, m = 1) {
    .Call(`_sousmarin_get_cov_matrix_sphere`, grid_nrow, a, m)
}

#' @export
get_cov_matrix_tent <- function(grid_nrow, a = 2, sigma = 1) {
    .Call(`_sousmarin_get_cov_matrix_tent`, grid_nrow, a, sigma)
}

