# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
set_seed <- function(seed) {
    invisible(.Call('_sousmarin_set_seed', PACKAGE = 'sousmarin', seed))
}

#' @export
print_xor_state <- function() {
    invisible(.Call('_sousmarin_print_xor_state', PACKAGE = 'sousmarin'))
}

#' @export
xorunif <- function(n, min = 0, max = 1) {
    .Call('_sousmarin_xorunif', PACKAGE = 'sousmarin', n, min, max)
}

#' Multiply a number by two
#'
#'
#' @export
double_me <- function(x) {
    .Call('_sousmarin_double_me', PACKAGE = 'sousmarin', x)
}

#' @export
say_hello <- function(x) {
    invisible(.Call('_sousmarin_say_hello', PACKAGE = 'sousmarin', x))
}

#' @export
test_threads <- function() {
    invisible(.Call('_sousmarin_test_threads', PACKAGE = 'sousmarin'))
}

